export const siteLinks = {
  instagram: 'https://www.instagram.com/capia3d',
  wallapop: 'https://es.wallapop.com/user/nicolasy-75461383',
  whatsapp: '34684710130',
  email: 'hola@capia3d.com',
}

export const content = {
  es: {
    nav: { work: 'Trabajos', process: 'Cómo funciona', about: 'Sobre mí', buy: 'Comprar', menu: 'Abrir menú', close: 'Cerrar menú' },
    hero: { eyebrow: 'Diseño e impresión 3D personalizada', title: 'Objetos diseñados para ser tuyos.', intro: 'Creo deck boxes, accesorios para cartas y piezas útiles que se adaptan a tus ideas, tus colores y tu forma de usarlos.', imageAlts: ['Funda para gafas de Snoopy personalizada por Capia 3D', 'Deck box personalizada creada por Capia 3D', 'Funda para gafas personalizada creada por Capia 3D'], noteLabel: 'Cada pieza', note: 'Personalizada para ti' },
    work: { eyebrow: 'Trabajo seleccionado', title: 'Ideas que toman forma.', intro: 'No son productos cerrados. Cada tipo de pieza es un punto de partida que podemos adaptar a ti.' },
    custom: { eyebrow: 'Hecho a tu medida', title: 'El color, el texto y los detalles también forman parte del diseño.', body: 'Cuéntame qué tienes en mente. Podemos partir de uno de estos trabajos o crear algo completamente nuevo.', link: 'Empezar un proyecto' },
    process: { eyebrow: 'Cómo funciona', title: 'De una idea a una pieza real.', steps: [{ title: 'Cuéntame tu idea', body: 'Hablamos de lo que necesitas, cómo lo usarás y qué quieres personalizar.' }, { title: 'Lo diseño', body: 'Convierto la idea en un diseño preparado para funcionar y durar.' }, { title: 'Lo imprimo', body: 'Elijo el material y reviso cada detalle durante la fabricación.' }, { title: 'Te lo envío', body: 'La pieza terminada viaja protegida y lista para usar.' }] },
    instagram: { title: 'Lo último creado por Capia 3D.', link: 'Seguir @capia3d', alt: 'Trabajo reciente de Capia 3D' },
    about: { eyebrow: 'Detrás de Capia 3D', title: 'Diseñar, probar y hacer las cosas un poco mejor.', paragraphs: ['Capia 3D nace de disfrutar resolviendo pequeñas necesidades con diseño e impresión 3D.', 'Cada encargo es una conversación. Me interesa entender cómo vas a usar la pieza y convertir esa idea en algo personal, útil y bien terminado.'], link: 'Ver el día a día en Instagram' },
    final: { eyebrow: 'Tu idea puede ser la siguiente', title: '¿Tienes en mente algo que todavía no existe?', body: 'Escríbeme y vemos juntos cómo convertirlo en una pieza hecha para ti.' },
    buySheet: { eyebrow: 'Elige cómo continuar', title: '¿Dónde quieres comprar?', intro: 'Encuentra piezas disponibles o háblame directamente para crear algo personalizado.', wallapop: 'Ver productos disponibles', whatsapp: 'Pedir algo personalizado', close: 'Cerrar' },
    whatsappMessage: 'Hola, he visto tus trabajos en la web de Capia 3D y me gustaría hacer un pedido personalizado.',
    product: { back: 'Volver a trabajos', what: 'Qué es', uses: 'Para qué sirve', examples: 'Ejemplos realizados', example: 'ejemplo', personalized: 'Siempre personalizable', related: 'Sigue explorando', relatedTitle: 'Otros trabajos que pueden interesarte' },
    footer: { tagline: 'Objetos personalizados, diseñados e impresos en 3D.', contact: 'Contacto' },
  },
  en: {
    nav: { work: 'Work', process: 'How it works', about: 'About', buy: 'Buy', menu: 'Open menu', close: 'Close menu' },
    hero: { eyebrow: 'Custom 3D design and printing', title: 'Objects designed to be yours.', intro: 'I create deck boxes, card accessories and useful objects shaped around your ideas, your colours and the way you use them.', imageAlts: ['Custom Snoopy glasses case by Capia 3D', 'Custom deck box created by Capia 3D', 'Custom glasses case created by Capia 3D'], noteLabel: 'Every piece', note: 'Made personal to you' },
    work: { eyebrow: 'Selected work', title: 'Ideas taking shape.', intro: 'These are not fixed products. Each type of object is a starting point that can be adapted to you.' },
    custom: { eyebrow: 'Made for you', title: 'Colour, text and details are all part of the design.', body: 'Tell me what you have in mind. We can start from one of these projects or create something completely new.', link: 'Start a project' },
    process: { eyebrow: 'How it works', title: 'From an idea to a real object.', steps: [{ title: 'Tell me your idea', body: 'We talk about what you need, how you will use it and what you want to personalise.' }, { title: 'I design it', body: 'I turn the idea into a design made to work well and last.' }, { title: 'I print it', body: 'I choose the material and check every detail during production.' }, { title: 'I ship it', body: 'The finished piece travels protected and ready to use.' }] },
    instagram: { title: 'Latest creations by Capia 3D.', link: 'Follow @capia3d', alt: 'Recent work by Capia 3D' },
    about: { eyebrow: 'Behind Capia 3D', title: 'Designing, testing and making things a little better.', paragraphs: ['Capia 3D began with the simple pleasure of solving everyday needs through design and 3D printing.', 'Every commission starts with a conversation. I want to understand how you will use the object and turn that idea into something personal, useful and carefully finished.'], link: 'Follow the process on Instagram' },
    final: { eyebrow: 'Your idea could be next', title: 'Thinking of something that does not exist yet?', body: 'Send me a message and let’s work out how to turn it into an object made for you.' },
    buySheet: { eyebrow: 'Choose how to continue', title: 'Where would you like to buy?', intro: 'Find available pieces or talk to me directly about creating something personal.', wallapop: 'See available products', whatsapp: 'Request something custom', close: 'Close' },
    whatsappMessage: 'Hi, I found your work through the Capia 3D website and I would like to place a custom order.',
    product: { back: 'Back to work', what: 'What it is', uses: 'What it is for', examples: 'Previous examples', example: 'example', personalized: 'Always personal', related: 'Keep exploring', relatedTitle: 'Other work you may like' },
    footer: { tagline: 'Personal objects, designed and 3D printed.', contact: 'Contact' },
  },
}

export const products = [
  {
    slug: 'deck-boxes', cover: 'products/deck-box-v2-simple/deck-box-v2-simple_7.png',
    gallery: ['products/deck-box-v2-simple/deck-box-v2-simple_7.png', 'products/deck-box-v2-simple/deck-box-v2-simple_other_4.png', 'products/deck-box-v2-simple/deck-box-v2-simple_other_3.png', 'products/deck-box-v2-top-loader-sideboard/deck-box-v2-top-loader-sideboard_2.png', 'products/deck-box-v2-top-loader-trail-sideboard/deck-box-v2-top-loader-trail-sideboard_7.png', 'products/deck-box-magnetic-60/deck-box-magnetic-60-other_2.png'],
    related: ['card-dividers'],
    es: { kicker: 'Juegos de cartas', title: 'Deck boxes personalizadas', short: 'Cajas diseñadas alrededor de tu mazo, tus cartas y tu estilo.', intro: 'Una deck box protege el mazo y, al mismo tiempo, puede convertirse en una parte más de su identidad.', whatTitle: 'Una caja creada alrededor de tu forma de jugar.', what: ['Cada deck box se diseña para guardar y proteger cartas con funda simple o doble, con opciones para distintos tamaños de mazo.', 'A partir de ahí, la pieza puede adaptarse con colores, texto, relieves, espacio para sideboard, dados o una carta visible.'], usesTitle: 'Protección, orden y personalidad.', uses: [{ title: 'Transportar tu mazo', body: 'Mantiene las cartas protegidas y organizadas dentro de la mochila.' }, { title: 'Organizar accesorios', body: 'Puede integrar espacios para dados, fichas, sideboard y otros elementos.' }, { title: 'Representar tu estilo', body: 'Colores, nombres y detalles hacen que la caja forme parte del mazo.' }], examplesTitle: 'Una idea, muchas versiones.', examplesIntro: 'Estas piezas ya fueron creadas para otros jugadores. Tu versión puede partir de ellas sin tener que ser igual.', personalizationTitle: 'Tu mazo no es igual a los demás. Su caja tampoco tiene por qué serlo.', personalization: 'Podemos elegir tamaño, cierre, distribución, colores y elementos gráficos para crear una combinación propia.' },
    en: { kicker: 'Trading card games', title: 'Custom deck boxes', short: 'Cases designed around your deck, your cards and your style.', intro: 'A deck box protects your cards and can also become part of your deck’s identity.', whatTitle: 'A case shaped around the way you play.', what: ['Each deck box is designed to store and protect single- or double-sleeved cards, with options for different deck sizes.', 'From there, it can be adapted with colours, text, embossed details, sideboard space, dice storage or a visible feature card.'], usesTitle: 'Protection, organisation and personality.', uses: [{ title: 'Carry your deck', body: 'Keeps cards protected and organised inside your bag.' }, { title: 'Organise accessories', body: 'Can include spaces for dice, tokens, sideboards and other essentials.' }, { title: 'Express your style', body: 'Colours, names and details make the box part of the deck.' }], examplesTitle: 'One idea, many versions.', examplesIntro: 'These pieces were created for other players. Yours can start from them without having to look the same.', personalizationTitle: 'Your deck is not like everyone else’s. Its box does not have to be either.', personalization: 'We can choose the size, closure, internal layout, colours and graphic details to create your own combination.' },
  },
  {
    slug: 'card-dividers', cover: 'products/separators/separators_multicolor_1.png',
    gallery: ['products/separators/separators_multicolor_1.png', 'products/separators/separator_example_1_800x600.jpg', 'products/separators/separator_example_2_800x600.jpg', 'products/separators/separator_example_4_800x600.jpg', 'products/separators/separators_artifact_1.png', 'products/separators/separator_example_6_800x600.jpg'],
    related: ['deck-boxes'],
    es: { kicker: 'Organización de cartas', title: 'Separadores personalizados', short: 'Una forma clara y visual de ordenar una colección de cartas.', intro: 'Los separadores permiten encontrar cada tipo de carta rápidamente y aportan color e identidad a la colección.', whatTitle: 'Organización diseñada para tu colección.', what: ['Son piezas impresas en 3D con una pestaña visible que ayuda a dividir cartas por color, tipo, colección o cualquier sistema que tenga sentido para ti.', 'El icono, el texto, los colores y la cantidad pueden adaptarse a la forma en que organizas tus cajas.'], usesTitle: 'Todo en su sitio, de un vistazo.', uses: [{ title: 'Clasificar cartas', body: 'Separa colores, tipos, expansiones o categorías personales.' }, { title: 'Encontrar más rápido', body: 'Las pestañas visibles evitan revisar montones completos.' }, { title: 'Crear un sistema propio', body: 'Los símbolos y textos pueden adaptarse a tu manera de coleccionar.' }], examplesTitle: 'Distintos sistemas, el mismo orden.', examplesIntro: 'Ejemplos de colores, símbolos y conjuntos creados para distintas colecciones.', personalizationTitle: 'Tu colección decide las categorías.', personalization: 'Podemos adaptar iconos, textos, colores, alturas y número de separadores para que encajen en tu sistema.' },
    en: { kicker: 'Card organisation', title: 'Custom card dividers', short: 'A clear, visual way to organise a card collection.', intro: 'Dividers make each type of card easier to find while adding colour and identity to a collection.', whatTitle: 'Organisation designed for your collection.', what: ['These are 3D-printed pieces with a visible tab that can divide cards by colour, type, set or any system that makes sense to you.', 'Icons, text, colours and quantities can all be adapted to the way you organise your boxes.'], usesTitle: 'Everything in place at a glance.', uses: [{ title: 'Classify cards', body: 'Separate colours, types, sets or personal categories.' }, { title: 'Find cards faster', body: 'Visible tabs remove the need to search through full stacks.' }, { title: 'Build your own system', body: 'Symbols and text can match the way you collect.' }], examplesTitle: 'Different systems, the same clarity.', examplesIntro: 'Examples of colours, symbols and sets created for different collections.', personalizationTitle: 'Your collection defines the categories.', personalization: 'We can adapt icons, wording, colours, heights and quantities so the dividers fit your system.' },
  },
]

export const productBySlug = new Map(products.map((product) => [product.slug, product]))
